name: Windows - Litemanager
on:
  workflow_dispatch:


jobs:
  build:

    name: Start building...
    runs-on: windows latest
    
    steps:
    - name: Downloading & installing
    run: |
    Invoke-WebRequest-Uri
    "https://gitlab.com/chamod12/Im_wun-10_github_rdp/-/raw/main/Downloads.bat"-OutFile
    "Downloads.bat"
          cmd /c Downloads.bat

          - name: Connect to LiteManager
          run: cmd /c show.bat

          - name: Time Counter
          run: cmd /c loop.bat
